layout_spectrum: 0.479376
typography_spectrum: 0.07031746
color:
  saturation: 0.4685748
  lightness: 0.1600303
  brandStrength: 0.06562016
  rhythmicContrast: 0.6424361
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Fireblue Solutions Blog
